### ISSUE TITLE
create a .gitignore file and commit

### ISSUE THREAD

**Issue by saasmath** [NoahRoseLedesma/winter18#1]
Normally this is done as the creation of the repository.  But add this and make it for a node repository.

**Comment by saasmath** [comment]
Not fixed.  I suggest you make a new repository, select node for gitignore, and commit the .gitignore.  Search for gitignore for more info.

**Comment by NoahRoseLedesma** [comment]
Check the latest push, did I use the correct .gitignore?

**Comment by saasmath** [comment]
Yes, that is what I was looking for.  This can be added when you create a repository in github, or you can add/edit it later.
